from django.urls import path, include
from .views import *
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('v1/api/llm', llm_invoke, name='llm_invoke'),
    path('v1/api/register', register_user, name='register_user'),
    path('v1/api/token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('v1/api/token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('v1/api/login', login_user, name='login_user'),
    path('v1/api/logout', logout_user, name='logout_user'),
    path('v1/api/ping', ping, name='ping'),
    path('v1/api/check-device', check_device, name='check_device'),
    path('v2/api/sign-language/recognize-poc', sign_to_text),
    path('v3/api/sign-language/recognize', sign_to_text_combine),
    path('v5/api/sign-language/recognize', sign_to_text),
    path('v1/api/sign-language/recognize-from-minio', recognize_sign_from_minio_video, name='recognize_from_minio'),
    path('v1/api/users', get_users, name='get_users'),
    path('v1/api/user/<int:user_id>', user_profile, name='user_profile'),
    path('v1/api/text-to-sign-smooth', text_to_sign_smooth, name='text_to_sign'),
    path('v1/api/friend-request/send/<int:receiver_id>', send_friend_request, name='send_friend_request'),
    path('v1/api/friend-request/respond/<int:request_id>/<str:action>', respond_friend_request, name='respond_friend_request'),
    path('v1/api/recognize', json_to_text, name='json_to_text'),
    path('v1/api/friend-request', get_friend_requests, name='get_friend_requests'),
    path('v1/api/relationships', list_relationships, name='list_relationships'),
    path('v1/api/friend-request/cancel/<int:request_id>', cancel_friend_request, name='cancel_friend_request'),
    path('v1/api/upload-image', upload_image, name='upload_image'),
    path('v1/api/message/send', send_message, name='send_message'),
    path('v1/api/conversation/<int:conversation_id>/messages', get_messages, name='get_messages'),
    path('v1/api/pin-conversation/<int:conversation_id>', toggle_pin_conversation),
    path('v1/api/text-chunking/', text_chunking),
    path('v1/api/text-to-speech', text_to_speech),
    path('v1/api/training-words', get_training_words, name='get_training_words'),
    path('v1/api/training-words/add', add_training_word, name='add_training_word'),
    path('v1/api/training-words/update', update_training_word, name='update_training_word'),
    path('v1/api/training-words/feedback', add_training_word_feedback, name='add_training_word_feedback'),
    path('v1/api/upload-file/start', start_upload, name='start_upload'),
    path('v1/api/upload-file/chunk', upload_chunk, name='upload_chunk'),
    path('v1/api/upload-file/finish', finish_upload, name='finish_upload'),
    path('v1/api/upload-file/capture-mediapine', upload_capture_mediapine, name='upload_capture_mediapine'),
    path('v1/api/upload-file/upload-video', upload_video, name='upload_video'),
    path('v1/api/delete-file/delete-video', delete_video, name='delete_video'),
    path('v1/api/e-learning/status', get_learning_status, name='get_learning_status'),
    path("v1/api/e-learning/lessons", lessons_search_view, name="lessons_search"),
    path("v1/api/e-learning/word-complete", mark_word, name="mark_word_completed"),
    path("v1/api/e-learning/notebook", get_user_notebook, name="get_user_notebook"),
    path("v1/api/e-learning/notebook/manage", manage_user_notebook, name="manage_user_notebook"),
]