# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sign_recognition.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16sign_recognition.proto\x12\x04sign\"+\n\x08Landmark\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\x8a\x01\n\x05\x46rame\x12\x1f\n\x07midEyes\x18\x01 \x01(\x0b\x32\x0e.sign.Landmark\x12 \n\x08leftHand\x18\x02 \x03(\x0b\x32\x0e.sign.Landmark\x12!\n\trightHand\x18\x03 \x03(\x0b\x32\x0e.sign.Landmark\x12\x1b\n\x03lip\x18\x04 \x03(\x0b\x32\x0e.sign.Landmark\"o\n\x10RecognizeRequest\x12\x1b\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x0b.sign.Frame\x12\x15\n\rprevious_word\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x15\n\rlanguage_code\x18\x04 \x01(\t\"4\n\nPrediction\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"E\n\x11RecognizeResponse\x12!\n\x07results\x18\x01 \x03(\x0b\x32\x10.sign.Prediction\x12\r\n\x05\x65rror\x18\x02 \x01(\t2V\n\x16SignRecognitionService\x12<\n\tRecognize\x12\x16.sign.RecognizeRequest\x1a\x17.sign.RecognizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sign_recognition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LANDMARK']._serialized_start=32
  _globals['_LANDMARK']._serialized_end=75
  _globals['_FRAME']._serialized_start=78
  _globals['_FRAME']._serialized_end=216
  _globals['_RECOGNIZEREQUEST']._serialized_start=218
  _globals['_RECOGNIZEREQUEST']._serialized_end=329
  _globals['_PREDICTION']._serialized_start=331
  _globals['_PREDICTION']._serialized_end=383
  _globals['_RECOGNIZERESPONSE']._serialized_start=385
  _globals['_RECOGNIZERESPONSE']._serialized_end=454
  _globals['_SIGNRECOGNITIONSERVICE']._serialized_start=456
  _globals['_SIGNRECOGNITIONSERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
